### ISSUE TITLE
Reducing duplicate CSS

### ISSUE THREAD

**Issue by jim-rosales** [wcisco17/Capstone-Project-1#2]
When you finding yourself writing the same CSS rule multiple times for different section. This will allow you to write less code and make more project more maintainable. 

For example instead of doing the following: 
```CSS
.mbl-nav {
  display: none;
}
.mbl-1 {
  display: none;
}
.mbl-2 {
      display: none;
}
.mbl-3 {
  display: none;
}
.main-cover-mbl {
  display: none;
}
.saf-nav {
  display: none;
}
#head-6 {
  display: none;
}
.sf-tn-1 {
  display: none;
}
.saf-ctn-2 {
  display: none;
}
#saf-head-3 {
display: none;
}
.saf-box-1 {
  display: none;
}
.saf-box-2 {
  display: none;
}
.saf-header-1 {
  display: none;
}
.saf-ctn-3 {
  display: none;
}
#saf-header-1 {
  display: none;
}
```
It is recommended to do the following instead:
``` CSS
.mbl-nav,
.mbl-1,
.mbl-2,
.mbl-3,
.main-cover-mbl,
.saf-nav,
#head-6,
.sf-tn-1,
.saf-ctn-2,
#saf-head-3,
.saf-box-1,
.saf-box-2,
.saf-header-1,
.saf-ctn-3,
#saf-header-1 {
  display: none;
}
```
This allows you to go from 46 lines of CSS to 17
https://github.com/wcisco17/Capstone-Project-1/blob/f053b8d3ba71245a550a8ec0a07b47fa01656d0b/css/style.css#L298-L344
